In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("sales_raw_500.xlsx")

In [3]:
data = df.copy()

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 520 entries, 0 to 519
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Order_ID    520 non-null    int64
 1   Order_Date  502 non-null    datetime64[ns]
 2   Customer    520 non-null    object
 3   Region      520 non-null    object
 4   Product     520 non-null    object
 5   Sales       520 non-null    int64
 6   Cost        520 non-null    int64
dtypes: datetime64[ns](1), int64(3), object(3)
memory usage: 28.6+ KB

In [5]:
data.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

### Remove duplicate coloumns

In [6]:
data.duplicated().sum()

np.int64(20)

In [7]:
data.shape

(520, 7)

In [8]:
data = data.drop_duplicates()

In [9]:
data.shape

(500, 7)

### Handle missing data value

In [10]:
data[data['Order_Date'].isnull()]

     Order_ID Order_Date Customer Region  Product  Sales   Cost
11       1012        NaT   Anjali   West   Tablet  13675   9070
57       1058        NaT    Pooja  South   Mobile  65332  46052
63       1064        NaT   Suresh  South   Tablet  61531  38210
70       1071        NaT    Pooja  North  Printer  59321  51362
88       1089        NaT     Neha  South   Mobile  67070  53712
102      1103        NaT    Rohit  South  Printer  36890  25522
145      1146        NaT    Rahul   East   Tablet  54131  39472
162      1163        NaT    Rahul   East  Printer  20220  12721
171      1172        NaT    Rahul   East   Mobile  47437  28686
174      1175        NaT   Suresh   East  Printer   9082   5614
197      1198        NaT    Rahul   West   Laptop  46033  35570
231      1232        NaT    Priya  South  Monitor  74176  53924
243      1244        NaT   Anjali   East   Laptop  53237  38920
248      1249        NaT   Anjali   West   Tablet  12518   7792
329      1330        NaT    Kiran  North   Mobile  10798   7781
424      1425        NaT    Vikas  South   Mobile  44566  28865
456      1457        NaT    Priya   East  Monitor  44834  36847
498      1499        NaT    Pooja   West   Mobile  59266  44326

In [11]:
data['Order_Date'].isnull().mean() * 100

np.float64(3.5999999999999996)

In [12]:
data['Order_Date'] = pd.to_datetime(data['Order_Date'], errors='coerce')
# Agar kisi value ko date mein convert nahi kar sakte, toh Pandas error dene ke bajaye usko NaT bana deta hai.

In [13]:
data = data.dropna(subset=['Order_Date'])

In [14]:
data.head()

   Order_ID Order_Date Customer Region  Product  Sales   Cost
0      1001 2023-01-13    Rohit  South   Mobile  23289  19118
1      1002 2023-10-07     Aman   West   Laptop   8905   5593
2      1003 2023-11-05    Rahul  South  Monitor  59987  39959
3      1004 2024-02-19    Rahul  South  Printer  49597  33892
4      1005 2024-01-26   Anjali  North   Laptop  54797  34468

### Add new coloums

In [15]:
data['Profit'] =  data['Sales']-data['Cost']
data['Year'] = data['Order_Date'].dt.year
data['Month'] = data['Order_Date'].dt.month

In [16]:
data.head()

,Order_ID,Order_Date,Customer,Region,Product,Sales,Cost,Profit,Year,Month
0,1001,2023-01-13,Rohit,South,Mobile,23289,19118,4171,2023,1
1,1002,2023-10-07,Aman,West,Laptop,8905,5593,3312,2023,10
2,1003,2023-11-05,Rahul,South,Monitor,59987,39959,20028,2023,11
3,1004,2024-02-19,Rahul,South,Printer,49597,33892,15705,2024,2
4,1005,2024-01-26,Anjali,North,Laptop,54797,34468,20329,2024,1

In [17]:
data.dtypes

Order_ID               int64
Order_Date    datetime64[ns]
Customer              object
Region                object
Product               object
Sales                  int64
Cost                   int64
Profit                 int64
Year                   int32
Month                  int32
dtype: object

### save the file

In [ ]:
data.to_csv("Cleaned_Data.csv",)